##TASCA M3 T02

#en aquesta tasca treballaràs amb la llibreria numpy i amb les dades de la llibreria sklearn.datasets. D'aquesta llibreria descarrega el conjunt de dades denominat Iris.
Tingues en compte que Iris està conformada per diversos conjunts de dades, dins d'ells, el array denominat: “data” i “target”. També està composta per llistes, per exemple: “feature_*names” i “target_*names”.
Per a obtenir informació del dataset pots consultar el següent enllaç:
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html#sklearn.datasets.load_iris

In [2]:
#EXERCICI 1

#Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

from sklearn.datasets import load_iris
data = load_iris()
import numpy as np
data1=data.data 
data1
data1[:10]



array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
target=data.target
target
target[:10]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
#EXERCICI 2

#Concatena “data” i “features” en un nou array. Mostra els 5 primers registres. Solo se pueden concatenar por columnas porque no coinciden las filas

tablas=np.column_stack([data1, target])
tablas

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [6]:
#EXERCICI 3

#Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") 
#i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals

nombres = data.feature_names
nombres



['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
media_sepal=np.mean(data1[:,0])
media_petal=np.mean(data1[:,2])
desv_sepal=np.std(data1[:,0])
desv_petal=np.std(data1[:,2])

r_media_sepal =np.around(media_sepal, decimals=2)
r_media_petal =np.around(media_petal, decimals=2)
r_desv_sepal =np.around(desv_sepal, decimals=2)
r_desv_petal =np.around(desv_petal, decimals=2)


print(f" la media de la longitud del sepalo es {r_media_sepal}")
print(f" la media de la longitud del petalo es {r_media_petal}")
print(f" la desviación stand de la longitud del sepalo es {r_desv_sepal}")
print(f" la desviación stand de la longitud del petalo es {r_desv_petal}")

 la media de la longitud del sepalo es 5.84
 la media de la longitud del petalo es 3.76
 la desviación stand de la longitud del sepalo es 0.83
 la desviación stand de la longitud del petalo es 1.76


In [21]:
#EXERCICI 4

#Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

muestra=np.random.rand(20,4)
columnas= ['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

print(columnas)
print(muestra)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[0.49463253 0.01938031 0.01282901 0.65432963]
 [0.01912595 0.93319969 0.87733907 0.45021625]
 [0.36948271 0.34442201 0.07959553 0.04718595]
 [0.37166978 0.89789059 0.21529475 0.05350127]
 [0.41577121 0.80420598 0.49595031 0.25011315]
 [0.90366833 0.25295398 0.75994403 0.37009498]
 [0.55905878 0.98945514 0.31586853 0.79724149]
 [0.74938153 0.93996225 0.18391429 0.6130425 ]
 [0.49874745 0.66450227 0.71021115 0.29816674]
 [0.05962656 0.61346845 0.54011748 0.38087942]
 [0.35229042 0.6174986  0.13373218 0.8975965 ]
 [0.92489947 0.22253189 0.35676154 0.7980535 ]
 [0.59784419 0.19372825 0.14412455 0.33603389]
 [0.61553728 0.98090816 0.18530811 0.433952  ]
 [0.62704982 0.24308696 0.20207587 0.39136527]
 [0.11195699 0.24831418 0.90308492 0.6602359 ]
 [0.13397452 0.89410392 0.77542185 0.30572919]
 [0.13084669 0.60371824 0.42620496 0.81377657]
 [0.40438769 0.36438241 0.6214335  0.85199982]
 [0.70639709 0.14679328 

In [22]:
#EXERCICI 5

#Crea una matriu que mostri: 
#• La mitjana de cada característica per espècie. 
#• La desviació estàndard de cada característica per espècie.

matriu = data.target_names
print(f"Las flores para el que se han obtenido los datos son {matriu}")

Las flores para el que se han obtenido los datos son ['setosa' 'versicolor' 'virginica']


In [31]:
extraccion_columna = tablas[:, 4]   #la especie se define en la columna 4, pido esa columna
valores_unicos=np.unique(extraccion_columna)    #busco los valores unicos, que son 0, 1, 2
grouped_data ={}                                #me servirá para agrupar los datos

media=[]                                        #inicializo lista vacia donde se almacenaran los datos que calcule mas tarde
varianza=[]

media_calculada=np.mean(tablas, axis=0)         #calculara la media de todas las columnas
varianza_calculada=np.var(tablas, axis=0)       #calculará la var de todas las columnas

for value in valores_unicos:                    
    indices =np.where(extraccion_columna == value)      #encuentra los valores unicos de la columna 4. son los value
    grouped_data[value] = tablas[indices]               #agrupa las filas que tienen un valor unico en columna 4
    media.append(np.mean(grouped_data[value], axis=0))  #calcula la media de las filas agrupadas y almacena en la lista vacia que habia creado media
    varianza.append(np.var(grouped_data[value], axis=0))    #calcula la var de las filas agrupadas y almacena en la lista vacia que habia creado varianza
rdo= np.column_stack((media, varianza))                 #creo una matriz. Cada fila tiene la media y la varianza de las filas agrupadas por un valor unico
rdo
  


array([[5.006   , 3.428   , 1.462   , 0.246   , 0.      , 0.121764,
        0.140816, 0.029556, 0.010884, 0.      ],
       [5.936   , 2.77    , 4.26    , 1.326   , 1.      , 0.261104,
        0.0965  , 0.2164  , 0.038324, 0.      ],
       [6.588   , 2.974   , 5.552   , 2.026   , 2.      , 0.396256,
        0.101924, 0.298496, 0.073924, 0.      ]])

In [21]:
#EXERCICI 6
#• Calcula la quantitat de mostres per espècie.
columnas=tablas[:,4]            #extraigo la columna 4 que es donde se define la especie
muestras_especie=np.unique (columnas, return_counts=True) #np.unique me busca los valores unicos de columna 4, return_count=True me hace el recuento de cada valor unico
muestras_especie

(array([0., 1., 2.]), array([50, 50, 50], dtype=int64))

In [22]:
media

[array([5.006, 3.428, 1.462, 0.246, 0.   ]),
 array([5.936, 2.77 , 4.26 , 1.326, 1.   ]),
 array([6.588, 2.974, 5.552, 2.026, 2.   ])]

In [52]:
#• Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"
sepal_length=rdo[:,0]               #escojo la columna correspondiente a sepal_length
valor_maximo= np.max(sepal_length)  #le pido el valor maximo de la columna 
especie= rdo[:, 4]                  #escojo la columna donde me dice la especie
nombres_especies =np.array(["setosa", "versicolor", "virginica"])   #hago el array con el nombre de las especies
nombres_relacionados = nombres_especies[especie.astype(int)]        #astype(int) asigna los nombres de las especies con los numeros de la columna 4
indice_maximo =np.argmax(sepal_length)                              # me busca el numero del valor max. en mi caso es el 2
nombre_especie_maximo=nombres_relacionados[indice_maximo]           #me traduce ese indice 2 de arriba al nombre de la especie
nombre_especie_maximo


'virginica'

In [53]:
#EXERCICI 7
#Calcula la matriu de correlació entre les variables.  corrcoef
#• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 
#• Troba la mostra amb els pètals més grans.

matriz_correlación = np.corrcoef(tablas, rowvar=False) # rowvar=False me interpreta las columnas como variables
matriz_correlación


array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.95654733],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

In [60]:

#• Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 

longitud_petals = tablas[:, 2]      
media=np.mean(longitud_petals)
media
majors_media=tablas>media       #si solo hiciera esto me daria una tabla de True y False
valores= tablas[majors_media]
valores


array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 3.9, 4.6, 5. , 4.4, 4.9, 5.4, 4.8,
       4.8, 4.3, 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 5.7, 3.8, 5.1, 3.8,
       5.4, 5.1, 4.6, 5.1, 4.8, 5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 5. , 5.5, 4.9, 4.4, 5.1, 5. , 4.5, 4.4, 5. ,
       5.1, 3.8, 4.8, 5.1, 3.8, 4.6, 5.3, 5. , 7. , 4.7, 6.4, 4.5, 6.9,
       4.9, 5.5, 4. , 6.5, 4.6, 5.7, 4.5, 6.3, 4.7, 4.9, 6.6, 4.6, 5.2,
       3.9, 5. , 5.9, 4.2, 6. , 4. , 6.1, 4.7, 5.6, 6.7, 4.4, 5.6, 4.5,
       5.8, 4.1, 6.2, 4.5, 5.6, 3.9, 5.9, 4.8, 6.1, 4. , 6.3, 4.9, 6.1,
       4.7, 6.4, 4.3, 6.6, 4.4, 6.8, 4.8, 6.7, 5. , 6. , 4.5, 5.7, 5.5,
       3.8, 5.5, 5.8, 3.9, 6. , 5.1, 5.4, 4.5, 6. , 4.5, 6.7, 4.7, 6.3,
       4.4, 5.6, 4.1, 5.5, 4. , 5.5, 4.4, 6.1, 4.6, 5.8, 4. , 5. , 5.6,
       4.2, 5.7, 4.2, 5.7, 4.2, 6.2, 4.3, 5.1, 5.7, 4.1, 6.3, 6. , 5.8,
       5.1, 7.1, 5.9, 6.3, 5.6, 6.5, 5.8, 7.6, 6.6, 4.9, 4.5, 7.3, 6.3,
       6.7, 5.8, 7.2, 6.1, 6.5, 5.1, 6.4, 5.3, 6.8, 5.5, 5.7, 5.

In [65]:
#• Troba la mostra amb els pètals més grans.
longitud_petals = tablas[:, 2]  
anchura_petals = tablas[:, 3]  
max_long=np.max(longitud_petals)
max_anch=np.max(anchura_petals)
petal_mes_gran = np.vstack([max_long,max_anch ])
petal_mes_gran




array([[6.9],
       [2.5]])

In [87]:
#EXERCICI 8
#Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals. 


sepal_length=tablas[:,0]               
media_sepal_lenght= np.mean(sepal_length)
petal_lenght=tablas[:,2]
media_petal_lenght= np.mean(petal_lenght)
especie= rdo[:, 4]  
nombres_especies =np.array(["setosa", "versicolor", "virginica"])   #hago el array con el nombre de las especies
nombres_relacionados = nombres_especies[especie.astype(int)]        #astype(int) asigna los nombres de las especies con los numeros de la columna 4
diferencia_max =np.argmax(np.abs(media_sepal_lenght-media_petal_lenght)) #abs me da la dif absoluta. argmax me da el indice de la dif maxima que necesitaré para cruzar con el nombre especie
nombre_especie_diferencia=nombres_relacionados[diferencia_max]       #me traduce ese indice de arriba al nombre de la especie
nombre_especie_diferencia


'setosa'